apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ddshop-deploy
  labels:
    app: ddshop
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: ddshop
    spec:
      containers:
        - name: ddshop-app
          image: cngoh1/ddshop-app:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: uwsgi
              containerPort: 8001
        - name: ddshop-web
          image: cngoh1/ddshop-web:2.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: ddshop-svc-nodeport
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      nodePort: 30443
      protocol: TCP
      name: https
  selector:
    app: ddshop
