apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ddshop-deploy
  labels:
    app: ddshop
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: ddshop
    spec:
      containers:
        - name: ddshop-app
          image: cngoh1/ddshop-app
          imagePullPolicy: IfNotPresent
          ports:
            - name: uwsgi
              containerPort: 8001
        - name: ddshop-web
          image: cngoh1/ddshop-web
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: ddshop-svc-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    app: ddshop
