FROM nginx

RUN mkdir -p /var/www/app/ddshop
RUN mkdir -p /etc/nginx/sites-available
RUN mkdir -p /etc/nginx/sites-enabled
 
WORKDIR /var/www/app/ddshop
COPY ./media ./media
COPY ./uwsgi_params ./
COPY ./static ./static

COPY ddshop-nginx.conf /etc/nginx/conf.d/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
